name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install arm toolchains
      run: sudo apt install gcc-arm-none-eabi gdb-multiarch
    - name: make bootloader
      run: |
        cd bootloader/F1
        make alt-link
    - name: make cli
      run: |
        cd cli
        make
